# 查找相应目录下所有包含CMakeLists.txt文件的子目录,并add_subdirectory
function(router)
    file(GLOB WALK *)
    foreach(ITEM IN LISTS WALK)
        cmake_path(APPEND CMAKE_FILE ${ITEM} CMakeLists.txt)
        if(EXISTS ${CMAKE_FILE})
            add_subdirectory(${ITEM})
        endif()
    endforeach()
endfunction()
function(router_source_files PATTERN)
    file(GLOB WALK LIST_DIRECTORIES FALSE "${PATTERN}")
    foreach(ITEM IN LISTS WALK)
        cmake_path(GET ITEM STEM LAST_ONLY PROJ)
        add_executable(${PROJ} ${ITEM})
    endforeach()
endfunction()